#!/bin/bash
set -x 

derive_cluster_details_infra()
{
 path=$(pwd)
 ## Get kubeconfig file into infra-setup gitlab runner pod
 mkdir ~/.kube; mkdir $path/azure
 cp  $path/azoebs_aks_name/config ~/.kube/config
 cp $path/azoebs_aks_name/config $path/azure/
}
 
setup_cluster_config_test()
{
 path=$(pwd)
 mkdir ~/.kube
 cp  $path/azure/config ~/.kube/config
}

if [[ $1 == "infra-setup" ]]; then
 derive_cluster_details_infra;
elif [[ $1 == "litmus-test" ]]; then
 setup_cluster_config_test;
else echo "invalid job type"; exit 1
fi 

