#!/bin/bash
set -x 

derive_cluster_details_infra()
{
 
 ## Get kubeconfig file into infra-setup gitlab runner pod
 mkdir ~/.kube; mkdir azure
 cp  /openebs/e2e-azure/azoebs_aks_name/config ~/.kube/config
 cp /openebs/e2e-azure/azoebs_aks_name/config azure/
}
 
setup_cluster_config_test()
{
 mkdir ~/.kube
 cp  azure/config ~/.kube/config
}

if [[ $1 == "infra-setup" ]]; then
 derive_cluster_details_infra;
elif [[ $1 == "litmus-test" ]]; then
 setup_cluster_config_test;
else echo "invalid job type"; exit 1
fi 
