#!/bin/bash
set -e

AZ_REPO=$(lsb_release -cs)
echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | \
    sudo tee /etc/apt/sources.list.d/azure-cli.list

curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -

sudo apt-get install apt-transport-https
sudo apt-get update && sudo apt-get install azure-cli

#installing Tree
sudo apt install tree

echo "Checking Azure CLI Version"
az -v
echo $AZURE_USER
az login -u $AZURE_USER -p $AZURE_PASSWORD
echo "Setup azure cluster"
git clone https://github.com/harshvkarn/litmus.git
cd litmus
git checkout azure-support
cd k8s/azure
echo "creating  cluster"

ansible-playbook create-k8s-cluster.yml -v --extra-vars "azure_username=$AZURE_USER azure_password=$AZURE_PASSWORD"

sleep 30
kubectl get nodes

wget https://raw.githubusercontent.com/openebs/litmus/master/hack/rbac.yaml
kubectl apply -f rbac.yaml

cat ~/.kube/config 
cd ../../..
echo $KUBECONFIG

mkdir azoebs_aks_name

cat ~/.kube/config > /openebs/e2e-azure/azoebs_aks_name/admin.conf
cat ~/.kube/config > /openebs/e2e-azure/azoebs_aks_name/config 
#copy cluster name to artifact
pwd
tree ../
cat /atulabhi/e2e-azure/litmus/k8s/azure/oebs_aks_name > /openebs/e2e-azure/azoebs_aks_name/oebs_aks_name
 
kubectl create configmap kubeconfig --from-file=/openebs/e2e-azure/azoebs_aks_name/admin.conf -n litmus
