#!/bin/bash
set -e

#---------------------Runner Cleanup-----------------------------------

kubectl get po -n gitlab-runner
kubectl get pods -n gitlab-runner -o go-template --template '{{range .items}}{{.metadata.name}} {{.metadata.creationTimestamp}}{{"\n"}}{{end}}' | awk '$2 <= "'$(date -d'now-6 hours' -Ins --utc | sed 's/+0000/Z/')'" { print $1 }' | grep "runner.*project-2" | xargs --no-run-if-empty kubectl delete pod -n gitlab-runner


echo "Checking Azure CLI Version"
az -v
az login -u $AZURE_USER -p $AZURE_PASSWORD
echo "Setup azure cluster"
git clone https://github.com/openebs/litmus.git
cd litmus
cd k8s/azure/k8s-installer
echo "creating  cluster"

ansible-playbook create-k8s-cluster.yml -v --extra-vars "nodes=3 node_size=Standard_D3"

sleep 30
kubectl get nodes

wget https://raw.githubusercontent.com/openebs/litmus/master/hack/rbac.yaml
kubectl apply -f rbac.yaml

cd ../../../..

mkdir azoebs_aks_name

cat ~/.kube/config > /openebs/e2e-azure/azoebs_aks_name/admin.conf
cat ~/.kube/config > /openebs/e2e-azure/azoebs_aks_name/config 
#copy cluster name to artifact
cat ~/logs/azure_clusters > /openebs/e2e-azure/azoebs_aks_name/azure_clusters
 
kubectl create configmap kubeconfig --from-file=/openebs/e2e-azure/azoebs_aks_name/admin.conf -n litmus
