#!/bin/bash
set -x

#################
## ENVIRONMENT ##
#################

## https://github.com/openebs/litmus/blob/master/apps/crunchy-postgres/deployers/test_vars.yml 
run_id="cstor";test_name=$(${utils_path}/generate_test_name testcase=crunchy-loadgen metadata=${run_id})

###################
## DEPENDENCIES  ##
###################

${utils_path}/setup_dependencies litmus-test

## Clone the litmus repo, navigate to litmus root 
git clone https://github.com/openebs/litmus.git
cd litmus 

############################
## LITMUS PRECONDITIONING ##
############################

cp apps/crunchy-postgres/workload/run_litmus_test.yml run_test.yml
: << EOF
  ------------------------------------------------------------------------------------
 | specAttribute        | kind     | jiva               | cStor-sparse                 |
  ------------------------------------------------------------------------------------
 | litmusJobLabel       | jobSpec  | postgres-loadjob   | postgres-loadjob-cstor       |
 | appNamespace         | env      | app-pgres-ns       | postgres-cstor               |
 | runID                | env(add) |    -               | cstor 
  ------------------------------------------------------------------------------------
EOF

cp apps/cassandra/workload/run_litmus_test.yml run_test.yml

sed -i -e 's/loadgen: postgres-loadjob/loadgen: postgres-loadjob-cstor/g' \
-e 's/value: app-pgres-ns/value: postgres-cstor/g' run_test.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' run_test.yml
#################
## RUNNER MAIN ##
#################

echo "Running the litmus test.."
${utils_path}/litmus_job_runner label='loadgen:postgres-loadjob-cstor' job=run_test.yml
${utils_path}/task_delimiter;

echo "Dumping state of cluster post job run"; echo ""
${utils_path}/dump_cluster_state;
${utils_path}/task_delimiter;

#################
## GET RESULT  ##
#################

## Check the test status & result from the litmus result custom resource
${utils_path}/get_litmus_result ${test_name}

